# /plan 命令 - 制定创作计划
# Gemini CLI 格式（TOML）

[plan]
description = "基于故事规格制定技术实现方案"
category = "methodology"
execute_immediately = false
confirmation_message = "即将制定创作技术方案。"

[plan.parameters.script]
type = "script_path"
value = ".specify/scripts/bash/plan-story.sh"
value_ps = ".specify\\scripts\\powershell\\plan-story.ps1"

[plan.prompts.main]
template = """
基于澄清后的规格，制定具体的创作技术方案。

## 执行步骤

### 1. 加载前置文档
运行脚本检查并加载：
- 宪法文件：`memory/novel-constitution.md`
- 规格文件：`stories/*/specification.md`
- 澄清记录（如已运行 `/clarify`）

### 2. 制定创作计划
创建 `stories/*/creative-plan.md`：

```markdown
# 创作计划

## 元数据
- 版本：1.0.0
- 创建日期：[YYYY-MM-DD]
- 基于规格版本：[版本号]

## 写作方法选择

### 选定方法
- 方法：[三幕结构/英雄之旅/故事圈等]
- 选择理由：[为什么适合]
- 应用方式：[如何应用]

## 章节架构设计

### 总体规划
- 总章数：[基于目标字数]
- 章节长度：[2000-3000字/章]
- 分卷安排：[如适用]

### 结构映射
[根据方法映射关键节点到章节]

### 节奏设计
- 开篇钩子：第[X]章
- 第一个高潮：第[X]章
- 中点转折：第[X]章
- 最大危机：第[X]章
- 最终高潮：第[X]章

## 人物体系设计

### 主角设计
- 初始状态：[起点]
- 成长弧线：[变化轨迹]
- 核心冲突：[内在vs外在]

### 配角功能
[每个重要配角的功能定位]

## 世界观构建

### 核心设定
- 世界规则：[规则体系]
- 社会结构：[组织形式]

### 设定展开计划
- 第一层（开篇）：[基础设定]
- 第二层（发展）：[深入设定]
- 第三层（高潮）：[核心秘密]

## 情节技术设计

### 冲突升级路径
1. 初级冲突：[个人层面]
2. 中级冲突：[团体层面]
3. 高级冲突：[世界层面]

### 悬念设置
- 主悬念：[贯穿全文]
- 章节悬念：[每章钩子]

## 技术决策记录

| 决策 | 选择 | 理由 | 风险 |
|------|------|------|------|
| POV | [选择] | [理由] | [风险] |
| 时间线 | [选择] | [理由] | [风险] |
| 叙事节奏 | [选择] | [理由] | [风险] |

## 质量保证计划

### 自检清单
- [ ] 逻辑一致性检查点
- [ ] 人物行为合理性
- [ ] 世界观自洽性

### 验证节点
- 每5章：小循环验证
- 每卷：大循环验证
```

提示下一步：运行 `/tasks` 生成任务清单。
"""

[plan.outputs]
file_pattern = "stories/{story_name}/creative-plan.md"
format = "markdown"