description = "检查情节逻辑，发现潜在的情节漏洞"

prompt = """
检查情节逻辑，发现并修复潜在问题。

用户要求：{{args}}

## 执行步骤

### 1. 执行情节检查
使用 run_shell_command 执行检查脚本：.specify/scripts/bash/check-plot.sh

### 2. 读取相关文件
加载检查所需文件：
- 使用 glob_files 查找 "stories/**/story.md" - 故事大纲
- 使用 glob_files 查找 "stories/**/outline.md" - 章节规划
- 使用 glob_files 查找 "stories/**/chapters/**/*.md" - 已写章节
- spec/tracking/plot-tracker.json - 情节追踪

### 3. 执行多维度检查

**因果逻辑检查**
```
检查项目：
□ 事件因果关系是否合理
□ 人物动机是否充分
□ 行为是否符合性格
□ 结果是否合乎逻辑
```

**伏笔回收检查**
```
伏笔追踪：
- 第2章埋下的线索 → ⚠️ 未回收
- 第5章的暗示 → ✅ 第8章回应
- 第7章的道具 → ⚠️ 未再出现
```

**冲突发展检查**
```
冲突曲线：
开端 ──┐
      │    ╱╲
      │   ╱  ╲  ← 第一次高潮
      │  ╱    ╲
      └─┴──────┴─→
        5  10  15  20 (章节)

问题：第12-14章冲突平缓，需要加强
```

**角色行为一致性**
```
角色逻辑检查：
⚠️ 李明在第6章性格突变
⚠️ 王芳的能力前后不一致
✅ 张三的成长轨迹合理
```

### 4. 生成问题报告

# 情节检查报告

## 发现的问题

### 严重问题（需立即修复）
1. **逻辑矛盾**
   - 位置：第8章
   - 问题：时间线冲突
   - 建议：调整事件顺序

### 中等问题（建议修复）
1. **伏笔未回收**
   - 位置：第2章设置
   - 内容：神秘信件
   - 建议：在第15章回应

### 轻微问题（可选优化）
1. **节奏拖沓**
   - 位置：第12-14章
   - 问题：冲突不足
   - 建议：增加次要冲突

## 修复建议
[具体修改方案]

### 5. 提供修复方案
```
修复优先级：
1. 立即：修正第8章时间线
2. 本周：回收第2章伏笔
3. 后续：优化12-14章节奏
```

### 6. 完成报告
✅ 情节检查完成！
- 检查章节：[数量]
- 发现问题：[数量]
- 严重程度：[评级]
- 建议：优先处理[问题类型]

## 注意事项
- 定期运行检查
- 优先修复逻辑问题
- 保持伏笔清单
- 注意节奏控制
"""