description = "管理章节，包括列表、重命名、调整顺序等操作"

prompt = """
管理小说章节，执行各种章节操作。

用户要求：{{args}}

## 执行步骤

### 1. 解析操作类型
根据参数判断：
- list/列表 - 显示所有章节
- rename/重命名 - 修改章节标题
- move/移动 - 调整章节顺序
- split/拆分 - 将长章节拆分
- merge/合并 - 合并短章节
- stats/统计 - 章节字数统计

### 2. 获取章节信息
读取章节目录：
```bash
使用 glob_files 查找 "stories/**/chapters/**/*.md"
```

### 3. 执行具体操作

**列表章节**
显示格式：
```
章节列表：
第1章：开端之日 (2,500字) ✓
第2章：意外相遇 (2,300字) ✓
第3章：初露端倪 (2,100字) ✓
第4章：[待写]
总进度：3/20章 (15%)
```

**重命名章节**
使用 edit_file 修改章节文件的标题行。

**移动章节**
1. 重命名文件调整顺序
2. 更新 outline.md 中的章节列表
3. 调整相关引用

**拆分章节**
1. 读取原章节内容
2. 找到合适的分割点
3. 创建两个新章节文件
4. 更新大纲

**合并章节**
1. 读取要合并的章节
2. 合并内容
3. 创建新章节文件
4. 删除原文件

**统计信息**
```
章节统计：
- 已写：10章
- 待写：15章
- 总字数：25,000字
- 平均每章：2,500字
- 最长：第7章（3,200字）
- 最短：第3章（2,100字）
```

### 4. 更新相关文件
根据操作更新：
- outline.md - 章节列表
- tracking/progress.json - 进度跟踪

### 5. 完成报告
✅ 章节[操作]完成！
- 操作：[具体操作]
- 影响：[影响的章节]
- 当前：[总章节数]
- 下一步：[建议]

## 注意事项
- 保持章节编号连续
- 移动时注意情节连贯
- 拆分点要自然
- 合并要检查过渡
"""