description = "规划详细的章节结构和情节安排"

prompt = """
基于故事大纲制定详细的章节规划，智能应用写作方法。

用户需求：{{args}}

## 执行步骤

### 1. 读取配置和方法
读取 .specify/config.json 的 "method" 字段：
- 如果是 "hybrid"，检查 "hybridScheme" 详细方案
- 参考对应模板：spec/presets/[method]/outline.md

### 2. 查找当前故事目录
使用 glob_files 查找 "stories/**/story.md" 文件，确定当前故事目录。

### 3. 初始化章节文件
使用 run_shell_command 执行：.specify/scripts/bash/setup-outline.sh

### 4. 加载故事大纲
使用 read_file 读取找到的 story.md 文件，理解故事内容。

### 5. 动态章节规划

**选择章节模式**
请先选择适合的章节模式：

1. **标准模式**（推荐初学者）
   - 每章2500-3000字，单次完成
   - 总计300章完成全书
   - 适合日更和稳定连载

2. **分节模式**（推荐进阶创作）
   - 每章分3节，总计7500-9000字
   - 采用智能分割比例（非等分）
   - 总计100章完成全书

3. **场景模式**（推荐专业作者）
   - 按场景写作，每场景2000-2500字
   - 3-4个场景组成一章
   - 灵活组合，后期调整

### 6. 智能章节分配

**根据内容类型标注每章**
分析每章特性，推荐分割策略：

示例规划：
```
第1章：开篇钩子【标准模式 2500字】
第2章：人物登场【三节模式 7500字】
第3章：初次冲突【四节-动作型 9500字】
第4章：日常过渡【三节模式 7500字】
第5章：关键转折【四节-悬念型 9500字】
第6章：情感铺垫【四节-情感型 9500字】
```

**节奏曲线设计**
- 开篇（1-3章）：标准模式，快速入戏
- 发展（4-8章）：分节模式，充分展开
- 高潮（9-10章）：动作型分割，紧张刺激
- 收束（11-12章）：情感型分割，余韵悠长

### 7. 应用写作方法

**三幕结构**
- 第一幕：25%章节，建立设置
- 第二幕：50%章节，冲突发展
- 第三幕：25%章节，高潮解决

**英雄之旅**
将12个阶段合理分配到章节中。

**故事圈**
8个步骤循环安排，每步2-3章。

**七点结构**
精确定位7个关键节点：
- 钩子（第1章）
- 情节点1（25%处）
- 收紧点（37%处）
- 中点（50%处）
- 情节点2（75%处）
- 黑暗时刻（90%处）
- 解决（结尾）

**皮克斯公式**
6步因果链条贯穿全书。

**雪花十步**
基于场景列表驱动章节。

**混合方法**
- 主线按主方法
- 支线按次方法
- 章节内按微观方法

### 8. 生成章节规划
确定故事目录后，使用 write_file 在该目录下创建 outline.md：

# 章节规划

## 总体结构
- 总章节数：[数量]
- 每章字数：[范围]
- 更新计划：[频率]

## 方法映射
[说明每章对应的方法节点]

## 卷部划分
[如有多卷，划分主题]

## 详细章节
### 第一章：[标题]
- 字数：[目标]
- 要点：[3-5个]
- 方法节点：[对应位置]

[继续其他章节...]

### 9. 完成报告
✅ 章节规划完成！
- 方法：[使用的结构]
- 章节：[总数]
- 预计：[总字数]
- 下一步：使用 /write 开始创作

## 注意事项
- 严格按照方法要求分配节奏
- 关键节点位置必须准确
- 混合方法要协调好层级
"""