description = "创建故事大纲，包括主题、角色、世界观等核心设定"

prompt = """
创建完整的故事大纲，智能应用写作方法模板。

用户描述：{{args}}

## 执行步骤

### 1. 读取配置和选择模板
首先读取 .specify/config.json 获取 "method" 字段：
- three-act → 三幕结构
- hero-journey → 英雄之旅
- story-circle → 故事圈
- seven-point → 七点结构
- pixar-formula → 皮克斯公式
- snowflake → 雪花十步

如未设置，提示使用 /method 命令。

### 2. 创建故事文件
使用 run_shell_command 获取当前日期：date '+%Y-%m-%d'
使用 run_shell_command 创建故事目录：.specify/scripts/bash/create-new-story.sh

解析脚本输出的 JSON，获取 STORY_NAME 和 STORY_FILE。

### 3. 应用方法模板
根据 method 使用对应的故事结构模板（参考 spec/presets/[method]/story.md）：

**三幕结构**：建立-对抗-解决
**英雄之旅**：12个阶段的成长历程
**故事圈**：8步循环的内在变化
**七点结构**：7个关键节点
**皮克斯公式**：6步故事公式
**雪花十步**：递进式构建

### 4. 生成大纲内容
使用 write_file 工具将以下内容写入 STORY_FILE：

# [故事名称]

## 故事概述
- 一句话描述
- 核心冲突
- 主题思想

## 角色设定
### 主角
- 姓名、年龄、背景
- 性格特点
- 成长弧线

### 重要配角
[按重要性列出]

## 世界观设定
- 时代背景
- 地理环境
- 社会规则
- 特殊设定

## 情节大纲
[根据选定的方法组织结构]

## 写作计划
- 预计字数
- 章节规划
- 时间安排

### 5. 完成报告
输出：
✅ 故事大纲创建成功！
- 故事：[名称]
- 文件：[路径]
- 方法：[使用的写作方法]
- 下一步：使用 /outline 规划详细章节

## 注意事项
- 必须使用 date 命令获取真实日期
- 脚本只运行一次，注意捕获输出
- 严格按照选定方法的模板结构
- 内容要具体，不要空泛
"""