description = "追踪写作进度和状态，生成进度报告"

prompt = """
追踪写作进度，管理创作状态。

用户要求：{{args}}

## 执行步骤

### 1. 读取追踪数据
加载所有追踪文件：
- spec/tracking/character-state.json
- spec/tracking/plot-tracker.json
- spec/tracking/relationships.json
- spec/tracking/timeline.json

### 2. 收集进度信息
使用 run_shell_command 执行：.specify/scripts/bash/track-progress.sh

解析参数判断模式：
- 无参数 - 显示完整追踪报告
- --brief - 显示简要信息
- --plot - 仅显示情节追踪
- --stats - 仅显示统计数据
- --check - 执行深度一致性检查
- --fix - 自动修复发现的问题

统计数据：
- 已写章节数
- 总字数
- 各章节状态
- 剩余工作量

### 3. 生成进度报告

**整体进度**
```
📊 写作进度报告

总体进度：████████░░ 40%
已完成：10/25章
总字数：25,000/60,000字

本周进度：
- 完成章节：2章
- 新增字数：5,000字
- 日均产出：714字
```

**章节详情**
```
章节状态：
✅ 第1章：完成（2,500字）
✅ 第2章：完成（2,300字）
📝 第3章：草稿（1,800字）
⏸️ 第4章：构思中
❌ 第5章：待写
```

**情节追踪**
```
主线进度：
[=====>    ] 50% - 冲突升级阶段

支线状态：
- 感情线：[===>  ] 30%
- 成长线：[====> ] 40%
```

**角色状态**
```
角色发展：
- 主角：成长期（第二阶段）
- 反派：潜伏期
- 配角A：关系转变中
```

### 4. 分析创作节奏
```
创作分析：
- 平均速度：500字/小时
- 最高产出：第7章（3,200字）
- 创作高峰：晚上8-10点
- 预计完成：30天后
```

### 5. 深度验证模式（--check）

当使用 --check 参数时，执行全面验证：

**基础验证**
- plot-tracker.json 与 outline.md 的一致性
- timeline.json 的时间逻辑
- relationships.json 的关系冲突
- character-state.json 的位置合理性

**角色深度验证**
- 加载 validation-rules.json 验证规则
- 扫描所有章节中的角色名称
- 对比 character-state.json 验证名称一致性
- 检查称呼是否符合 relationships.json
- 验证角色行为是否符合人设

**生成验证报告**
```
📊 深度验证报告
━━━━━━━━━━━━━━━━━━━
✅ 通过项目: 15/18

❌ 发现问题 (3):
1. [高] 第3章: 主角名错误
2. [中] 第7章: 称呼不一致
3. [低] 第12章: 时间线跳跃

🔧 可自动修复: 2个
📝 需人工确认: 1个
```

### 6. 自动修复模式（--fix）

当使用 --fix 参数时，自动修复简单问题：

**可修复范围**
- 角色名称错误 - 根据 validation-rules.json 替换
- 固定称呼错误 - 自动修正为正确称呼
- 简单拼写错误 - 修正明显的 typo

**修复报告**
```
🔧 自动修复报告
━━━━━━━━━━━━━━━
✅ 已修复: 2个问题
- 第3章: 名称已修正
- 第7章: 称呼已调整

⚠️ 需人工处理: 1个
- 第12章: 时间线需补充
```

### 7. 智能分析与建议
```
📝 创作建议：
1. 当前节奏良好，保持每日更新
2. 第10章是关键转折，需要重点准备
3. 支线进度偏慢，建议下章推进
4. 人物关系可以增加冲突
```

### 8. 节奏分析报告

**章节结构分析**
```
章节模式分布：
- 标准章节：45% (135/300章)
- 分节章节：30% (90/300章)
- 场景组合：25% (75/300章)

内容类型分布：
- 对话密集：25%
- 动作场面：20%
- 情感铺垫：30%
- 悬念转折：15%
- 过渡连接：10%

节奏曲线评估：
起伏度：★★★★☆
张弛度：★★★★☆
悬念感：★★★☆☆
建议：下章可增加动作场面
```

### 9. 更新追踪文件
使用 edit_file 更新各追踪文件的最新状态。

### 10. 可视化进度报告

生成结构化报告：
```
📊 综合追踪报告
━━━━━━━━━━━━━━━━━━━━━━━━━━
[进度条] ████████░░░░░░░ 25%

🎯 下一步建议：
1. 第65章前回收伏笔
2. 加强主角与反派冲突
3. 补充第二卷时间线

⚠️ 需要关注：
- 角色B已5章未出场
- 支线剧情进度滞后
- 第45章时间跳跃需说明
```

### 11. 完成报告
✅ 进度追踪完成！
- 总进度：[百分比]
- 本周产出：[字数]
- 预计完成：[日期]
- 下一步：[建议]

## 注意事项
- 定期更新追踪数据
- 关注关键节点进度
- 及时调整创作计划
- 保持稳定产出
"""